### ISSUE TITLE
minor issue in tutorial

### ISSUE THREAD

**Issue by LukeAndersonTrocme** [mmosmond/sparg#1]

**Comment by mmosmond** [comment]
Hi Luke, many thanks for checking out the tutorial and noting the issue. Instead of changing the tutorial itself (and continuing to do so as dependencies evolve) I've added versions to the requirements. Hope that keeps the tutorial working indefinitely...

**Comment by LukeAndersonTrocme** [comment]
That's great. Thanks for the quick turnaround! Looking forward to playing around with this tutorial.
